php/presupuesto/src/Entity/DetallePresupuesto.php
<?php

namespace App\Entity;

use App\Repository\DetallePresupuestoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DetallePresupuestoRepository::class)]
class DetallePresupuesto
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'detallePresupuestos')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Presupuesto $id_presupuesto = null;

    #[ORM\Column]
    private ?int $cantidad = null;

    #[ORM\Column]
    private ?float $precio_initario = null;

    #[ORM\Column(nullable: true)]
    private ?float $sub_total = null;

    #[ORM\Column]
    private ?int $item_presupuesto_id = null;

    #[ORM\ManyToOne(inversedBy: 'detallePresupuestos')]
    #[ORM\JoinColumn(nullable: false)]
    private ?TipoProducto $id_tipo_item = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdPresupuesto(): ?Presupuesto
    {
        return $this->id_presupuesto;
    }

    public function setIdPresupuesto(?Presupuesto $id_presupuesto): static
    {
        $this->id_presupuesto = $id_presupuesto;

        return $this;
    }

    public function getCantidad(): ?int
    {
        return $this->cantidad;
    }

    public function setCantidad(int $cantidad): static
    {
        $this->cantidad = $cantidad;

        return $this;
    }

    public function getPrecioInitario(): ?float
    {
        return $this->precio_initario;
    }

    public function setPrecioInitario(float $precio_initario): static
    {
        $this->precio_initario = $precio_initario;

        return $this;
    }

    public function getSubTotal(): ?float
    {
        return $this->sub_total;
    }

    public function setSubTotal(?float $sub_total): static
    {
        $this->sub_total = $sub_total;

        return $this;
    }

    public function getItemPresupuestoId(): ?int
    {
        return $this->item_presupuesto_id;
    }

    public function setItemPresupuestoId(int $item_presupuesto_id): static
    {
        $this->item_presupuesto_id = $item_presupuesto_id;

        return $this;
    }

    public function getIdTipoItem(): ?TipoProducto
    {
        return $this->id_tipo_item;
    }

    public function setIdTipoItem(?TipoProducto $id_tipo_item): static
    {
        $this->id_tipo_item = $id_tipo_item;

        return $this;
    }
}

php/presupuesto/src/Form/DetallePresupuestoType.php
<?php

namespace App\Form;

use App\Entity\DetallePresupuesto;
use App\Entity\Presupuesto;
use App\Entity\TipoProducto;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DetallePresupuestoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('cantidad', null, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('precio_initario', null, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('sub_total', null, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('item_presupuesto_id', null, [
                'attr' => ['class' => 'form-control']
            ])
            ->add('id_presupuesto', EntityType::class, [
                'class' => Presupuesto::class,
                'choice_label' => 'id',
                'attr' => ['class' => 'form-control']
            ])
            ->add('id_tipo_item', EntityType::class, [
                'class' => TipoProducto::class,
                'choice_label' => 'id',
                'attr' => ['class' => 'form-control']
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => DetallePresupuesto::class,
        ]);
    }
}

php/presupuesto/src/Controller/DetallePresupuestoController.php
<?php

namespace App\Controller;

use App\Entity\DetallePresupuesto;
use App\Form\DetallePresupuestoType;
use App\Repository\DetallePresupuestoRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/detalle/presupuesto')]
final class DetallePresupuestoController extends AbstractController
{
    #[Route(name: 'app_detalle_presupuesto_index', methods: ['GET'])]
    public function index(DetallePresupuestoRepository $detallePresupuestoRepository): Response
    {
        return $this->render('detalle_presupuesto/index.html.twig', [
            'detalle_presupuestos' => $detallePresupuestoRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_detalle_presupuesto_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $detallePresupuesto = new DetallePresupuesto();
        $form = $this->createForm(DetallePresupuestoType::class, $detallePresupuesto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($detallePresupuesto);
            $entityManager->flush();

            return $this->redirectToRoute('app_detalle_presupuesto_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('detalle_presupuesto/new.html.twig', [
            'detalle_presupuesto' => $detallePresupuesto,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_detalle_presupuesto_show', methods: ['GET'])]
    public function show(DetallePresupuesto $detallePresupuesto): Response
    {
        return $this->render('detalle_presupuesto/show.html.twig', [
            'detalle_presupuesto' => $detallePresupuesto,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_detalle_presupuesto_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, DetallePresupuesto $detallePresupuesto, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(DetallePresupuestoType::class, $detallePresupuesto);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_detalle_presupuesto_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('detalle_presupuesto/edit.html.twig', [
            'detalle_presupuesto' => $detallePresupuesto,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_detalle_presupuesto_delete', methods: ['POST'])]
    public function delete(Request $request, DetallePresupuesto $detallePresupuesto, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$detallePresupuesto->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($detallePresupuesto);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_detalle_presupuesto_index', [], Response::HTTP_SEE_OTHER);
    }
}

php/presupuesto/templates/detalle_presupuesto/_delete_form.html.twig
<form method="post" action="{{ path('app_detalle_presupuesto_delete', {'id': detalle_presupuesto.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ detalle_presupuesto.id) }}">
    <button class="btn">Delete</button>
</form>

php/presupuesto/templates/detalle_presupuesto/_form.html.twig
{# _form.html.twig para DetallePresupuestoType #}
{{ form_start(form) }}
<input type="hidden" name="_csrf_token" value="{{ csrf_token('form_action') }}">
<div class="container card border-secondary">
    <div class="form-group row">
        <div class="col-md-6">
            {{ form_label(form.presupuesto) }} <br>
            {{ form_widget(form.presupuesto) }}
        </div>
        <div class="col-md-6">
            {{ form_label(form.item) }} <br>
            {{ form_widget(form.item) }}
        </div>
    </div>
    <div class="form-group row">
        <div class="col-md-6">
            {{ form_label(form.cantidad) }} <br>
            {{ form_widget(form.cantidad) }}
        </div>
        <div class="col-md-6">
            {{ form_label(form.precio) }} <br>
            {{ form_widget(form.precio) }}
        </div>
    </div>
    <div class="form-group row mt-3">
        <div class="col-md-12 text-center">
            <button class="btn btn-primary">{{ button_label|default('Guardar') }}</button>
        </div>
    </div>
</div>
{{ form_end(form) }}

php/presupuesto/templates/detalle_presupuesto/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit DetallePresupuesto{% endblock %}

{% block body %}
    <h1>Edit DetallePresupuesto</h1>

    {{ include('detalle_presupuesto/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_detalle_presupuesto_index') }}">Listar</a>

    {{ include('detalle_presupuesto/_delete_form.html.twig') }}
{% endblock %}

php/presupuesto/templates/detalle_presupuesto/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}DetallePresupuesto index{% endblock %}

{% block body %}
    <h1>DetallePresupuesto index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Cantidad</th>
                <th>Precio_initario</th>
                <th>Sub_total</th>
                <th>Item_presupuesto_id</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for detalle_presupuesto in detalle_presupuestos %}
            <tr>
                <td>{{ detalle_presupuesto.id }}</td>
                <td>{{ detalle_presupuesto.cantidad }}</td>
                <td>{{ detalle_presupuesto.precioInitario }}</td>
                <td>{{ detalle_presupuesto.subTotal }}</td>
                <td>{{ detalle_presupuesto.itemPresupuestoId }}</td>
                <td>
                    <a href="{{ path('app_detalle_presupuesto_show', {'id': detalle_presupuesto.id}) }}">show</a>
                    <a href="{{ path('app_detalle_presupuesto_edit', {'id': detalle_presupuesto.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_detalle_presupuesto_new') }}">Create new</a>
{% endblock %}

php/presupuesto/templates/detalle_presupuesto/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New DetallePresupuesto{% endblock %}

{% block body %}
    <h1>Create new DetallePresupuesto</h1>

    {{ include('detalle_presupuesto/_form.html.twig') }}

    <a href="{{ path('app_detalle_presupuesto_index') }}">Listar</a>
{% endblock %}

php/presupuesto/templates/detalle_presupuesto/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}DetallePresupuesto{% endblock %}

{% block body %}
    <h1>DetallePresupuesto</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ detalle_presupuesto.id }}</td>
            </tr>
            <tr>
                <th>Cantidad</th>
                <td>{{ detalle_presupuesto.cantidad }}</td>
            </tr>
            <tr>
                <th>Precio_initario</th>
                <td>{{ detalle_presupuesto.precioInitario }}</td>
            </tr>
            <tr>
                <th>Sub_total</th>
                <td>{{ detalle_presupuesto.subTotal }}</td>
            </tr>
            <tr>
                <th>Item_presupuesto_id</th>
                <td>{{ detalle_presupuesto.itemPresupuestoId }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_detalle_presupuesto_index') }}">Listar</a>

    <a href="{{ path('app_detalle_presupuesto_edit', {'id': detalle_presupuesto.id}) }}">edit</a>

    {{ include('detalle_presupuesto/_delete_form.html.twig') }}
{% endblock %}